const reset = "\x1b[0m";
const yellow = "\x1b[33m";
const red = "\x1b[31m";
const bold = "\x1b[1m";

console.log(
  `${yellow}
[Monicon]

The '@monicon/runtime' package is not meant to be installed directly.

Please uninstall this package.
Monicon icons are generated by bundlers.

If you are seeing the error ${red}${bold}Failed to resolve import "@monicon/runtime"${reset}${yellow}, 
please ensure that the versions in your package.json and package-lock.json files are the same.
${reset}`
);
