<script setup lang="ts">
useHead({
  title: "Nuxt App",
  meta: [{ name: "description", content: "Generated by create turbo" }],
});
</script>

<template>
  <main>
    <Monicon name="mdi:home" :size="24" />
    <Monicon name="logos:active-campaign" />
    <Monicon name="logos:apache-superset-icon" />
    <Monicon name="lucide:badge-check" :size="24" :stroke-width="3" />
    <Monicon name="invalid:icon" />
  </main>
</template>

<style>
html,
body {
  margin: 0;
  padding: 0;
}

main {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background-color: #242424;
  color: rgba(255, 255, 255, 0.87);
}
</style>
